Imports:

In [2]:
import pandas as pd
import numpy as np
import yfinance as yf
import os
from datetime import datetime

Create Data Folders:

In [3]:
BASE_DIR = "../data"
PRICE_DIR = os.path.join(BASE_DIR, "prices")
FUND_DIR = os.path.join(BASE_DIR, "fundamentals")

os.makedirs(PRICE_DIR, exist_ok=True)
os.makedirs(FUND_DIR, exist_ok=True)

Download HDFC Bank Prices:

In [4]:
TICKER = "HDFCBANK.NS"
START_DATE = "2000-01-01"
END_DATE = datetime.today().strftime("%Y-%m-%d")

stock = yf.download(TICKER, start=START_DATE, end=END_DATE)
stock.to_csv(f"{PRICE_DIR}/HDFCBANK_prices.csv")

stock.head()

C:\Users\ASUS\AppData\Local\Temp\ipykernel_27028\240137754.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  stock = yf.download(TICKER, start=START_DATE, end=END_DATE)
[*********************100%***********************]  1 of 1 completed

Price            Close        High         Low        Open      Volume
Ticker     HDFCBANK.NS HDFCBANK.NS HDFCBANK.NS HDFCBANK.NS HDFCBANK.NS
Date
2000-01-03    6.877011    6.877011    6.715199    6.715199      665180
2000-01-04    7.030734    7.421105    6.917466    7.362449     3374200
2000-01-05    6.753629    7.034777    6.674745    6.877011     3196400
2000-01-06    6.808241    6.877011    6.686882    6.796105     1700520
2000-01-07    6.810265    6.917466    6.559456    6.559456     1702880

Download NIFTY Prices:

In [5]:
INDEX = "^NSEI"

index_data = yf.download(INDEX, start=START_DATE, end=END_DATE)
index_data.to_csv(f"{PRICE_DIR}/NIFTY_prices.csv")

index_data.head()

C:\Users\ASUS\AppData\Local\Temp\ipykernel_27028\1539831820.py:3: FutureWarning: YF.download() has changed argument auto_adjust default to True
  index_data = yf.download(INDEX, start=START_DATE, end=END_DATE)
[*********************100%***********************]  1 of 1 completed

Price             Close         High          Low         Open Volume
Ticker            ^NSEI        ^NSEI        ^NSEI        ^NSEI  ^NSEI
Date
2007-09-17  4494.649902  4549.049805  4482.850098  4518.450195      0
2007-09-18  4546.200195  4551.799805  4481.549805  4494.100098      0
2007-09-19  4732.350098  4739.000000  4550.250000  4550.250000      0
2007-09-20  4747.549805  4760.850098  4721.149902  4734.850098      0
2007-09-21  4837.549805  4855.700195  4733.700195  4752.950195      0

Download Financial Statements:

In [6]:
company = yf.Ticker(TICKER)

income_stmt = company.financials.T
balance_sheet = company.balance_sheet.T
cashflow_stmt = company.cashflow.T

Save Statements:

In [7]:
income_stmt.to_csv(f"{FUND_DIR}/income_statement.csv")
balance_sheet.to_csv(f"{FUND_DIR}/balance_sheet.csv")
cashflow_stmt.to_csv(f"{FUND_DIR}/cashflow_statement.csv")