Import Libraries:

In [1]:
import pandas as pd
import numpy as np
import os

Load Financial Statements:

In [2]:
BASE_DIR = "../data/fundamentals"

income = pd.read_csv(f"{BASE_DIR}/income_statement.csv", index_col=0)
balance = pd.read_csv(f"{BASE_DIR}/balance_sheet.csv", index_col=0)
cashflow = pd.read_csv(f"{BASE_DIR}/cashflow_statement.csv", index_col=0)

income.head(), cashflow.head()

(            Tax Effect Of Unusual Items  Tax Rate For Calcs  \
 2025-03-31                          0.0              0.2031
 2024-03-31                          0.0              0.1103
 2023-03-31                          0.0              0.2508
 2022-03-31                          0.0              0.2553
 2021-03-31                          NaN                 NaN

             Total Unusual Items  Total Unusual Items Excluding Goodwill  \
 2025-03-31                  NaN                                     NaN
 2024-03-31                  0.0                                     0.0
 2023-03-31                  NaN                                     NaN
 2022-03-31                  NaN                                     NaN
 2021-03-31                  NaN                                     NaN

             Net Income From Continuing Operation Net Minority Interest  \
 2025-03-31                                       6.735083e+11
 2024-03-31                                       6.226566e+11
 2023-03-31                                       4.954469e+11
 2022-03-31                                       3.860004e+11
 2021-03-31                                                NaN

             Reconciled Depreciation  Net Interest Income  Interest Expense  \
 2025-03-31             6.302130e+10         1.404486e+12      1.823477e+12
 2024-03-31             5.234830e+10         1.248003e+12      1.533923e+12
 2023-03-31             2.348970e+10         9.139885e+11      7.755382e+11
 2022-03-31             1.681690e+10         7.488395e+11      5.842975e+11
 2021-03-31                      NaN                  NaN               NaN

             Interest Income  Normalized Income  ...  \
 2025-03-31     3.227963e+12       6.735083e+11  ...
 2024-03-31     2.781926e+12       6.226566e+11  ...
 2023-03-31     1.689527e+12       4.954469e+11  ...
 2022-03-31     1.333137e+12       3.860004e+11  ...
 2021-03-31              NaN                NaN  ...

             Depreciation Income Statement  Selling General And Administration  \
 2025-03-31                   3.778410e+10                        1.124876e+12
 2024-03-31                   3.114730e+10                        9.517626e+11
 2023-03-31                   2.348970e+10                        4.002198e+11
 2022-03-31                   1.681690e+10                        3.202191e+11
 2021-03-31                            NaN                                 NaN

             General And Administrative Expense  Other Gand A  \
 2025-03-31                        1.124876e+12  2.927577e+11
 2024-03-31                        9.517626e+11  2.810208e+11
 2023-03-31                        4.002198e+11  2.004930e+11
 2022-03-31                        3.202191e+11  1.549314e+11
 2021-03-31                                 NaN           NaN

             Insurance And Claims  Salaries And Wages  Total Revenue  \
 2025-03-31          5.328671e+11        2.992517e+11   2.371508e+12
 2024-03-31          3.819658e+11        2.887760e+11   1.986934e+12
 2023-03-31          0.000000e+00        1.997268e+11   1.205375e+12
 2022-03-31          0.000000e+00        1.652877e+11   1.019414e+12
 2021-03-31                   NaN                 NaN            NaN

             Operating Revenue  Occupancy And Equipment  \
 2025-03-31       2.371508e+12             7.773360e+10
 2024-03-31       1.986934e+12             6.513150e+10
 2023-03-31       1.205375e+12             4.506990e+10
 2022-03-31       1.019414e+12             3.623600e+10
 2021-03-31                NaN                      NaN

             Other Non Interest Expense
 2025-03-31                         NaN
 2024-03-31                7.916980e+10
 2023-03-31                         NaN
 2022-03-31                         NaN
 2021-03-31                4.016488e+11

 [5 rows x 41 columns],
             Free Cash Flow  Repurchase Of Capital Stock  Repayment Of Debt  \
 2025-03-31    1.129220e+12                          NaN      -1.463101e+12
 2024-03-31    9.684844e+11                -2.300000e+09      -1.400298e+12
 2023-03-31    4.335803e+11                          NaN      -5.581136e+11
 2022-03-31    5.546938e+11                          NaN      -3.533257e+11
 2021-03-31             NaN                          NaN                NaN

             Issuance Of Debt  Issuance Of Capital Stock  Capital Expenditure  \
 2025-03-31      6.612263e+11                        NaN        -6.639730e+10
 2024-03-31      1.155775e+12               7.599730e+10        -5.383800e+10
 2023-03-31      1.022933e+12                        NaN        -4.362030e+10
 2022-03-31      7.229089e+11                        NaN        -2.632440e+10
 2021-03-31               NaN               0.000000e+00                  NaN

             Interest Paid Supplemental Data  \
 2025-03-31                     1.803804e+12
 2024-03-31                     1.407747e+12
 2023-03-31                     7.454878e+11
 2022-03-31                     5.798538e+11
 2021-03-31                              NaN

             Income Tax Paid Supplemental Data  End Cash Position  \
 2025-03-31                       1.954097e+11       1.982930e+12
 2024-03-31                       1.997534e+11       2.086031e+12
 2023-03-31                       1.636749e+11       1.387395e+12
 2022-03-31                       1.483816e+11       1.122031e+12
 2021-03-31                                NaN                NaN

             Other Cash Adjustment Outside Changein Cash  ...  \
 2025-03-31                                          NaN  ...
 2024-03-31                                 1.118171e+11  ...
 2023-03-31                                          NaN  ...
 2022-03-31                                          NaN  ...
 2021-03-31                                          NaN  ...

             Depreciation And Amortization  Amortization Cash Flow  \
 2025-03-31                   6.302130e+10            2.523720e+10
 2024-03-31                   5.234830e+10            2.120100e+10
 2023-03-31                   2.348970e+10            0.000000e+00
 2022-03-31                   1.681690e+10                     NaN
 2021-03-31                            NaN            0.000000e+00

             Amortization Of Intangibles  Depreciation  Operating Gains Losses  \
 2025-03-31                 2.523720e+10  3.778410e+10            1.313470e+10
 2024-03-31                 2.120100e+10  3.114730e+10            3.908700e+09
 2023-03-31                 0.000000e+00  2.348970e+10            9.873000e+08
 2022-03-31                          NaN  1.681690e+10           -2.155970e+10
 2021-03-31                 0.000000e+00           NaN                     NaN

             Gain Loss On Investment Securities  \
 2025-03-31                       -6.825000e+09
 2024-03-31                       -8.267000e+08
 2023-03-31                        7.203000e+08
 2022-03-31                       -1.674580e+10
 2021-03-31                                 NaN

             Net Foreign Currency Exchange Gain Loss  Gain Loss On Sale Of PPE  \
 2025-03-31                             2.018460e+10              -224900000.0
 2024-03-31                             5.554300e+09              -748000000.0
 2023-03-31                             2.767000e+08               -80600000.0
 2022-03-31                            -4.813000e+09                 -900000.0
 2021-03-31                                      NaN                       NaN

             Gain Loss On Sale Of Business  \
 2025-03-31                            NaN
 2024-03-31                  -7.341420e+10
 2023-03-31                            NaN
 2022-03-31                            NaN
 2021-03-31                            NaN

             Net Income From Continuing Operations
 2025-03-31                           6.865313e+11
 2024-03-31                           6.276319e+11
 2023-03-31                           4.962644e+11
 2022-03-31                           3.866030e+11
 2021-03-31                                    NaN

 [5 rows x 66 columns])

Inspect Cash Flow Columns:

In [3]:
cashflow.columns

Index(['Free Cash Flow', 'Repurchase Of Capital Stock', 'Repayment Of Debt',
       'Issuance Of Debt', 'Issuance Of Capital Stock', 'Capital Expenditure',
       'Interest Paid Supplemental Data', 'Income Tax Paid Supplemental Data',
       'End Cash Position', 'Other Cash Adjustment Outside Changein Cash',
       'Beginning Cash Position', 'Effect Of Exchange Rate Changes',
       'Changes In Cash', 'Financing Cash Flow',
       'Cash Flow From Continuing Financing Activities',
       'Net Other Financing Charges', 'Proceeds From Stock Option Exercised',
       'Cash Dividends Paid', 'Common Stock Dividend Paid',
       'Net Common Stock Issuance', 'Common Stock Payments',
       'Common Stock Issuance', 'Net Issuance Payments Of Debt',
       'Net Short Term Debt Issuance', 'Net Long Term Debt Issuance',
       'Long Term Debt Payments', 'Long Term Debt Issuance',
       'Investing Cash Flow', 'Cash Flow From Continuing Investing Activities',
       'Net Investment Purchase And Sale', 'Sale Of Investment',
       'Purchase Of Investment', 'Net Business Purchase And Sale',
       'Sale Of Business', 'Net PPE Purchase And Sale', 'Sale Of PPE',
       'Purchase Of PPE', 'Operating Cash Flow',
       'Cash Flow From Continuing Operating Activities', 'Taxes Refund Paid',
       'Change In Working Capital', 'Change In Other Working Capital',
       'Change In Other Current Liabilities', 'Change In Other Current Assets',
       'Change In Payables And Accrued Expense', 'Change In Accrued Expense',
       'Change In Payable', 'Change In Account Payable',
       'Change In Receivables', 'Changes In Account Receivables',
       'Other Non Cash Items', 'Stock Based Compensation',
       'Unrealized Gain Loss On Investment Securities', 'Deferred Tax',
       'Deferred Income Tax', 'Depreciation Amortization Depletion',
       'Depreciation And Amortization', 'Amortization Cash Flow',
       'Amortization Of Intangibles', 'Depreciation', 'Operating Gains Losses',
       'Gain Loss On Investment Securities',
       'Net Foreign Currency Exchange Gain Loss', 'Gain Loss On Sale Of PPE',
       'Gain Loss On Sale Of Business',
       'Net Income From Continuing Operations'],
      dtype='object')

Compute Free Cash Flow (FCF):

In [5]:
cashflow["FCF"] = (
    cashflow["Operating Cash Flow"] -
    cashflow["Capital Expenditure"]
)

In [7]:
cashflow[["Operating Cash Flow", "Capital Expenditure", "FCF"]]

            Operating Cash Flow  Capital Expenditure           FCF
2025-03-31         1.195617e+12        -6.639730e+10  1.262015e+12
2024-03-31         1.022322e+12        -5.383800e+10  1.076160e+12
2023-03-31         4.772006e+11        -4.362030e+10  5.208209e+11
2022-03-31         5.810182e+11        -2.632440e+10  6.073426e+11
2021-03-31                  NaN                  NaN           NaN

Handle Missing Values:

In [8]:
cashflow = cashflow.dropna(subset=["FCF"])

Sort by Time:

In [9]:
cashflow = cashflow.sort_index()

Save Clean FCF Data:

In [10]:
fcf_df = cashflow[["FCF"]]
fcf_df.to_csv("../data/fundamentals/fcf_clean.csv")

fcf_df

                     FCF
2022-03-31  6.073426e+11
2023-03-31  5.208209e+11
2024-03-31  1.076160e+12
2025-03-31  1.262015e+12