Load Beta (from CSV):

In [1]:
import pandas as pd

# Load beta estimated earlier
beta_df = pd.read_csv("../data/beta_hdfc.csv")
beta_df

        ticker      beta     alpha
0  HDFCBANK.NS  1.037092 -0.000092

Define WACC Inputs:

In [2]:
# Core financial inputs
risk_free_rate = 0.07          # 7% (India 10Y approx)
market_risk_premium = 0.06     # 6%
cost_of_debt = 0.08            # 8%
tax_rate = 0.25                # 25%

# Capital structure (can later be dynamic)
debt_weight = 0.30
equity_weight = 0.70

beta = beta_df["beta"].iloc[0]

Cost of Equity (CAPM):

Cost of Equity = Rf​+β(Rm​−Rf​)

In [5]:
cost_of_equity = risk_free_rate + beta * market_risk_premium
cost_of_equity

np.float64(0.1322255406298417)

Compute WACC:

WACC = E/V⋅Re ​+ D/V⋅Rd​⋅(1−T)

In [6]:
wacc = (
    equity_weight * cost_of_equity +
    debt_weight * cost_of_debt * (1 - tax_rate)
)

wacc

np.float64(0.1105578784408892)

Make WACC Dynamic:

In [7]:
wacc_df = pd.DataFrame({
    "ticker": ["HDFCBANK.NS"],
    "beta": [beta],
    "risk_free_rate": [risk_free_rate],
    "market_premium": [market_risk_premium],
    "cost_of_debt": [cost_of_debt],
    "tax_rate": [tax_rate],
    "equity_weight": [equity_weight],
    "debt_weight": [debt_weight],
    "wacc": [wacc]
})

wacc_df

,ticker,beta,risk_free_rate,market_premium,cost_of_debt,tax_rate,equity_weight,debt_weight,wacc
0,HDFCBANK.NS,1.037092,0.07,0.06,0.08,0.25,0.7,0.3,0.110558

Save WACC:

In [8]:
wacc_df.to_csv("../data/wacc_hdfc.csv", index=False)